#端口
server:
  port: 8888

#spring:
#  #数据源
#  datasource:
#    url: jdbc:mysql://127.0.0.1/test?useUnicode=true&characterEncoding=utf8&useSSL=true
#    driver-class-name: com.mysql.jdbc.Driver
#    data-username: root
#    data-password: root
#    #配置数据源的类型
#    type: org.apache.commons.dbcp2.BasicDataSource
#    type: org.springframework.jdbc.datasource.DriverManagerDataSource
spring:
  druid:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    max-active: 20
    initial-size: 5
    min-idle: 5
    max-idle: 10
    validation-query: select 1
    stat-view:
      login-username: admin
      login-password: admin
      allow:
      deny:
      url-mapping:
        - "/druid/*"

